#!/usr/bin/env bash

set -e

CONFIG="install"
SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

echo "Select a configuration file:"
echo "  1) Base"
echo "  2) OS Specific Packages"

read -rp "Select [1-2]: " CONFIG_SELECT

if [ "${CONFIG_SELECT}" == "1" ]; then
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}${SUFFIX}" "${@}"
elif [ "${CONFIG_SELECT}" == "2" ]; then
    source /etc/os-release
    case $ID in
        arch|manjaro)
            echo "Btw I'm running on Arch Linux"
            "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "arch${SUFFIX}" --plugin-dir "${BASEDIR}/dotbot-yay" "${@}"
            ;;
        debian)
            echo "Debian"
            sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${ID}${SUFFIX}" --plugin-dir "${BASEDIR}/dotbot_plugin_aptget" "${@}"
            ;;
        *)
            echo "Unknown distro ID: $ID, not doing anything special"
            ;;
    esac
else
    echo "Invalid selection"
    exit 1
fi
